name: JustHomes
version: "1.20"
description: Homes plugin, create home and enjoy.
api-version: "1.19"
authors: [Kondee3, marcelbpunkt]
main: me.kondi.justhomes.JustHomesPlugin
softdepend: [PlaceholderAPI]
commands:
  sethome:
    description: You can create homes with it.
    usage: /<command> <homename>
  home:
    description: Teleports you to your home.
    usage: /<command> <homename>
  spawn:
    description: Teleports you to your player spawn.
    usage: /<command>
  homes:
    description: Lists all your homes.
    usage: /<command>
  delhome:
    description: Deletes your home.
    usage: /<command> <homename>
  reloadlanguage:
    description: Reloads languages.
    usage: /<command>

permissions:
  justhomes.sethome:
    description: Allows you to create homes.
    default: true
  justhomes.home:
    description: Allows you to teleport to homes.
    default: true
  justhomes.spawn:
    description: Allows you to teleport to your player spawn.
    default: true
  justhomes.homes:
    description: Allows you to list your homes.
    default: true
  justhomes.delhome:
    description: Allows you to delete your homes.
    default: true
  justhomes.reloadlanguage:
    description: Allows you to fast reload language.
    default: op

